# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

# Force upgrade ESLint and add Flow present
- script: |
    npm install eslint@latest --save-dev 
    npm install @babel/preset-flow --save-dev 
  displayName: 'Upgrade ESLint and add Flow preset'

- script: |
    rm -rf node_modules package-lock.json
    npm install --include=dev --legacy-peer-deps
    npm run build
  displayName: 'npm install and build'
